In [1]:
import urx
import math
from math import *
import math3d as m3d
import numpy as np
import time
import plotly.graph_objects as go
import sys
import plotly.io as pio

In [ ]:
#Connection Establishment
robo = urx.Robot("127.0.0.1")

In [ ]:
robo.movej(( math.pi/2,-math.pi/2,math.pi/2,0,math.pi/2,math.pi),0.2,0.2,wait=False)

In [ ]:
robo.movej(( math.pi,-math.pi/2,-math.pi/36,0,math.pi/2,math.pi),0.2,0.2,wait=False)

In [ ]:
pio.renderers.default = "browser"

In [ ]:
current_data = robo.getl()
print(current_data)


In [ ]:
def EulerAngle(xtheta,ytheta,ztheta):
    xmatrix = np.matrix([[1,0,0],[0,cos(xtheta),-sin(xtheta)],[0,sin(xtheta),cos(xtheta)]])
    ymatrix = np.matrix([[cos(ytheta),0,sin(ytheta)],[0,1,0],[-sin(ytheta),0,cos(ytheta)]])
    zmatrix = np.matrix([[cos(ztheta),-sin(ztheta),0],[sin(ztheta),cos(ztheta),0],[0,0,1]])
    EulerAngleRot = zmatrix*ymatrix*xmatrix
    return EulerAngleRot


In [2]:
def OrientMatixRotation(axis,rotationvec,theta):
    comp1 = rotationvec * np.cos(theta)
    comp2 = np.cross(rotationvec,axis) * np.sin(theta)
    comp3 = (rotationvec * (np.dot(rotationvec,axis)))* (1 - np.cos(theta))
    Rodrigues = comp1 + comp2 + comp3
    return Rodrigues

In [ ]:
def rodrigues_vec_to_rotation_mat(rodrigues_vec):
    theta = np.linalg.norm(rodrigues_vec)
    if theta < sys.float_info.epsilon:              
        rotation_mat = np.eye(3, dtype=float)
    else:
        r = rodrigues_vec / theta
        I = np.eye(3, dtype=float)
        r_rT = np.array([
            [r[0]*r[0], r[0]*r[1], r[0]*r[2]],
            [r[1]*r[0], r[1]*r[1], r[1]*r[2]],
            [r[2]*r[0], r[2]*r[1], r[2]*r[2]]
        ])
        r_cross = np.array([
            [0, -r[2], r[1]],
            [r[2], 0, -r[0]],
            [-r[1], r[0], 0]
        ])
        rotation_mat = math.cos(theta) * I + (1 - math.cos(theta)) * r_rT + math.sin(theta) * r_cross
    return rotation_mat 

In [3]:
def FigVec(fig,vector1,vector2,vector3):
#     data = go.Scatter3d(x=[origin[0],vector1[0]],y=[origin[1],vector1[1]],z=[origin[2],vector1[2]],mode = 'markers', marker=dict(opacity = 0.5, color = ('rgb(204, 102, 0)')))
#     data1 = go.Scatter3d(x=[origin[0],vector2[0]],y=[origin[1],vector2[1]],z=[origin[2],vector2[2]],mode = 'markers', marker=dict(opacity = 0.5, color = ('rgb(204, 102, 0)')))
    data2 = go.Scatter3d(x=[vector3[0]],y=[vector3[1]],z=[vector3[2]],mode = 'markers', marker=dict(opacity = 0.5, color = ('rgb(204, 102, 0)')))
#     fig.add_trace(data)
#     fig.add_trace(data1)
    fig.add_trace(data2)
    return fig,[vector1,vector2,vector3]
    

In [ ]:
def rotsplit(R):
    vectorx1 = np.asarray([R1[0,0],R1[1,0],R1[2,0]])
    vectory1 = np.asarray([R1[0,1],R1[1,1],R1[2,1]])
    vectorz1 = np.asarray([R1[0,2],R1[1,2],R1[2,2]])
    return np.asarray([vectorx1,vectory1,vectorz1])

In [ ]:
# xtheta = current_data[3]
# ytheta = current_data[4]
# ztheta = current_data[5]

# R = EulerAngle(xtheta,ytheta,ztheta)
R= np.matrix([[ -0.0000003, -0.0000000, -1.0000000],[1.0000000, -0.0000003, -0.0000003],[-0.0000003, -1.0000000,  0.0000000 ]])
print(R)

origin = [0,0,0]
vectorx = np.asarray([R[0,0],R[1,0],R[2,0]])
vectory = np.asarray([R[0,1],R[1,1],R[2,1]])
vectorz = np.asarray([R[0,2],R[1,2],R[2,2]])

fig = go.Figure()
theta = np.linspace(0,2*pi,20)
phi = np.linspace(0,pi,10)
for i in range(0,len(theta)):
    for j in range(0,len(phi)):
        Rod_y = OrientMatixRotation(vectorx,vectory,theta[i])
#         fig = FigVec(fig,vectorx,Rod_y,vectorz)
        Rod_xy = OrientMatixRotation(Rod_y,vectorx,phi[j])
#         print(Rod_xy)
#         Rod_y1 = OrientMatixRotation(Rod_xy,Rod_y,theta[i])
        Rod_y1 = OrientMatixRotation(Rod_xy,Rod_y,theta[i])
#         print(Rod_xy)
#         print(Rod_y1)
#         print(vectorz)
#         fig,r = FigVec(fig,Rod_xy,Rod_y1,vectorz)
        fig,r = FigVec(fig,Rod_y,Rod_xy,Rod_y1)
#         print(r)
            
# R1 = EulerAngle(-0.01852074617501981,-0.11105406264394302,-0.9936417750535276)
# print(r)
# print(R1)

# print(fig.data)

fig.show()



In [ ]:
#stop robot
robo.stop()

In [ ]:
xtheta = -1.2114564411573427
ytheta = -1.2078672892093762
ztheta = 1.2092725333212169

R = EulerAngle(xtheta,ytheta,ztheta)
print(R)

vectorx = np.asarray([R[0,0],R[1,0],R[2,0]])
vectory = np.asarray([R[0,1],R[1,1],R[2,1]])
vectorz = np.asarray([R[0,2],R[1,2],R[2,2]])
print(vectorx,vectory,vectorz)

In [7]:
R= np.matrix([[ 1,0,0],[0,1,0],[0,0,1 ]])
print(R)

origin = [0,0,0]
vectorx =np.array( [1,0,0])
vectory =np.array( [0,1,0])
vectorz =np.array( [0,0,1 ])

RotationMatrix = []

fig = go.Figure()
theta = np.linspace(0,2*pi,20)
phi = np.linspace(0,pi,20)
# print(theta)
for i in phi:
    print(i)
    for j in theta:
        Rod_y = OrientMatixRotation(vectorx,vectory,j)
        Rod_z = OrientMatixRotation(vectorx,vectorz,j)
        fig,r = FigVec(fig,vectorx,Rod_y,Rod_z)
        R1 = np.asarray([vectorx,Rod_y,Rod_z])
        RotationMatrix.append(R1)
#         R1 = EulerAngle(Rod_y[0],Rod_y[1],Rod_y[2])
#         RMatrix = rotsplit(R1)
#         RotationMatrix.append(RMatrix)
#         R2 = EulerAngle(Rod_z[0],Rod_z[1],Rod_z[2])
#         RMatrix1 = rotsplit(R2)
#         RotationMatrix.append(RMatrix1)
        
        
        
#         for k in range(len(r)): 
#                 R1 = EulerAngle(r[k][0],r[k][1],r[k][2])
#                 vectorx1 = np.asarray([R1[0,0],R1[1,0],R1[2,0]])
#                 vectory1 = np.asarray([R1[0,1],R1[1,1],R1[2,1]])
#                 vectorz1 = np.asarray([R1[0,2],R1[1,2],R1[2,2]])
#                 RMatrix = np.asarray([vectorx1,vectory1,vectorz1])
#                 RotationMatrix.append(RMatrix)
                
    Rod_xy = OrientMatixRotation(Rod_y,vectorx,i)
    Rod_xz = OrientMatixRotation(Rod_y,Rod_z,i)
    
    vectorx = Rod_xy
    vectory = vectory
    vectorz = Rod_xz
#     R= np.asarray([Rod_xy,vectory,Rod_xz])
# #   fig,r = FigVec(fig,Rod_xy,vectory,Rod_xz)
# #         print(R)
#     RotationMatrix.append(np.transpose(R))
#     vectorx = np.asarray([R[0,0],R[1,0],R[2,0]])
#     vectory = np.asarray([R[0,1],R[1,1],R[2,1]])
#     vectorz = np.asarray([R[0,2],R[1,2],R[2,2]])
#     fig,r = FigVec(fig,vectorx,vectory,vectorz)
    
#         fig, r = FigVec(fig,vectorx,vectory,vectorz)
        
#         fig,r1 = FigVec(fig,vectorx,Rod_y,Rod_z)
        
# #         fig = FigVec(fig,vectorx,Rod_y,vectorz)
#         Rod_xy = OrientMatixRotation(Rod_y,vectorx,phi[j])
# #         print(Rod_xy)
# #         Rod_y1 = OrientMatixRotation(Rod_xy,Rod_y,theta[i])
#         Rod_y1 = OrientMatixRotation(Rod_xy,Rod_y,theta[i])
# #         print(Rod_xy)
# #         print(Rod_y1)
# #         print(vectorz)
# #         fig,r = FigVec(fig,Rod_xy,Rod_y1,vectorz)
#         fig,r = FigVec(fig,Rod_y,Rod_xy,Rod_y1)
# #         print(r)
# print(Rod_xy)          
# R1 = EulerAngle(-0.01852074617501981,-0.11105406264394302,-0.9936417750535276)
# print(r)
# print(R1)
# print(RotationMatrix)
# print(fig.data)
# print(len(phi),phi)
# print(len(RotationMatrix))
# # print(RotationMatrix)
fig.show()

[[1 0 0]
 [0 1 0]
 [0 0 1]]
0.0
0.16534698176788384
0.3306939635357677
0.4960409453036515
0.6613879270715354
0.8267349088394192
0.992081890607303
1.1574288723751869
1.3227758541430708
1.4881228359109546
1.6534698176788385
1.8188167994467224
1.984163781214606
2.14951076298249
2.3148577447503738
2.4802047265182576
2.6455517082861415
2.8108986900540254
2.9762456718219092
3.141592653589793


In [ ]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
np.asarray([a,b,c])

In [ ]:


# def FigVec(vector1,vector2,vector3):
#     origin = [0,0,0]
#     data = go.Scatter3d(x=[origin[0],vector1[0]],y=[origin[1],vector1[1]],z=[origin[2],vector1[2]],marker=dict(opacity = 0.5, color = ('rgb(204, 102, 0)')))
#     data1 = go.Scatter3d(x=[origin[a
0],vector2[0]],y=[origin[1],vector2[1]],z=[origin[2],vector2[2]],marker=dict(opacity = 0.5, color = ('rgb(204, 102, 255)')))
#     data2 = go.Scatter3d(x=[origin[0],vector3[0]],y=[origin[1],vector3[1]],z=[origin[2],vector3[2]],marker=dict(opacity = 0.5, color = ('rgb(255, 102, 255)')))
#     fig.add_trace(data)
#     fig.add_trace(data1)
#     fig.add_trace(data2)
#     return fig

# def plot_rot(R):
    
#     for i in range(0,len(R)):
#         vectorx = np.asarray([R[i,0,0],R[i,1,0],R[i,2,0]])
#         vectory = np.asarray([R[i,0,1],R[i,1,1],R[i,2,1]])
#         vectorz = np.asarray([R[i,0,2],R[i,1,2],R[i,2,2]])
#         fig = FigVec(vectorx,vectory,vectorz)
#     return fig

# R= np.array([[[ -0.0000003, -0.0000000, -1.0000000],[1.0000000, -0.0000003, -0.0000003],[-0.0000003, -1.0000000,  0.0000000 ]],[[-0.21581449,  0.        , -0.97643438],[ 0.97643438,  0.        , -0.21581449],[ 0.        , -1.        ,  0.        ]]])
# print(R)
# fig = go.Figure()
# fig = plot_rot(R)
# fig.show()