In [3]:
import urx
import math
import math3d as m3d
import numpy as np
import time

In [9]:
#Connection Establishment
robo = urx.Robot("172.16.101.225")
# robo = urx.Robot("127.0.0.1")

tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 68
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1092
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1454


In [11]:
#Home position
robo.movej(( 0,-math.pi/2,math.pi/2,0,math.pi/2,math.pi),0.2,0.2,wait=False)

In [ ]:
def getcurrentdata():
    xvalue = 0
    yvalue = 0
    zvalue = 0
    
    for i in range(10):
        value = robo.getl()
        xvalue += value[0]
        yvalue += value[1]
        zvalue += value[2]
        time.sleep(0.2)
    
    store = [xvalue,yvalue,zvalue]
    
    return store

In [ ]:
#Define movemnents : 
# Example : robo.movel((0,0,0.1,0,0,0),0.1,0.1,relative=True,wait=False) **Move 100mm in  positive z direction
stack = []

In [ ]:
#Make linear movement
robo.movel((stack),relative=True,wait=False)

In [ ]:
#record values
current_values = getcurrentdata()
print("Averaged Values : {}".format(current_values))

In [10]:
np.asarray(robo.getl())*1000

array([ -611.32716628,  -139.97226391,  -204.29798313, -1211.48040435,
       -1207.97440069,  1209.2648031 ])

In [ ]:
np.subtract([ -591.59344691,  -134.6548425 ,  -204.56507602],[-591.5067401192478,-135.3963755895251,-204.29899430975076])

In [ ]:
30 60
30 120
30 180
30 240
30 300
30 360
45 60
45 120
45 180
45 240
45 300
45 360
65 60
65 120
65 180
65 240
65 300
65 360
[array([-615.6572933 , -137.47226391, -195.63772909]),
 array([-615.6572933 , -142.47226391, -195.63772909]),
 array([-611.32716628, -144.97226391, -195.63772909]),
 array([-606.99703926, -142.47226391, -195.63772909]),
 array([-606.99703926, -137.47226391, -195.63772909]),
 array([-611.32716628, -134.97226391, -195.63772909]),
 array([-617.45089064, -136.43673   , -197.22691532]),
 array([-617.45089064, -143.50779782, -197.22691532]),
 array([-611.32716628, -147.04333172, -197.22691532]), 
 array([-605.20344192, -143.50779782, -197.22691532]),
 array([-605.20344192, -136.43673   , -197.22691532]),
 array([-611.32716628, -132.9011961 , -197.22691532]), 
 array([-619.17602195, -135.44072497, -200.07180051]),
 array([-619.17602195, -144.50380285, -200.07180051]),
 array([-611.32716628, -149.03534178, -200.07180051]),
 array([-603.47831061, -144.50380285, -200.07180051]),
 array([-603.47831061, -135.44072497, -200.07180051]),
 array([-611.32716628, -130.90918604, -200.07180051])]












In [ ]:
#Freedrive
robo.set_freedrive(1)

In [8]:
robo.getl()

[-0.6047061549963848,
 -0.13445940207668816,
 0.33802262595261556,
 -1.211541268120007,
 -1.2079236283405634,
 1.2092274020998512]

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/shivendra/virtual_robotics_urx/lib/python3.5/site-packages/urx/ursecmon.py", line 286, in run
    data = self._get_data()
  File "/home/shivendra/virtual_robotics_urx/lib/python3.5/site-packages/urx/ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer



In [ ]:
#Robot stop;
robo.stop()