In [2]:
import urx
import math
from math import *
import math3d as m3d
import numpy as np
import time
import plotly.graph_objects as go

In [3]:
#Connection Establishment
robo = urx.Robot("127.0.0.1")

tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 44
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 68
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1092
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1454


In [41]:
robo.movej(( math.pi/2,-math.pi/2,math.pi/2,0,math.pi/2,math.pi),0.2,0.2,wait=False)

In [1]:
robo.movej(( math.pi,-math.pi/2,-math.pi/36,0,math.pi/2,math.pi),0.2,0.2,wait=False)

NameError: name 'robo' is not defined

In [43]:
current_data = robo.getl()
print(current_data)


[0.4575023278594732, -0.5326372148968166, 0.48453401283584535, -3.8430936135891506e-07, -2.2214412958513097, 2.221441296307005]


In [51]:
def EulerAngle(xtheta,ytheta,ztheta):
    xmatrix = np.matrix([[1,0,0],[0,cos(xtheta),-sin(xtheta)],[0,sin(xtheta),cos(xtheta)]])
    ymatrix = np.matrix([[cos(ytheta),0,sin(ytheta)],[0,1,0],[-sin(ytheta),0,cos(ytheta)]])
    zmatrix = np.matrix([[cos(ztheta),-sin(ztheta),0],[sin(ztheta),cos(ztheta),0],[0,0,1]])
    EulerAngleRot = zmatrix*ymatrix*xmatrix
    return EulerAngleRot


In [52]:
def OrientMatixRotation(axis,rotationvec,theta):
    comp1 = rotationvec * np.cos(theta)
    comp2 = np.cross(rotationvec,axis) * np.sin(theta)
    comp3 = (rotationvec * (np.dot(rotationvec,axis)))* (1 - np.cos(theta))
    Rodrigues = comp1 + comp2 + comp3
    return Rodrigues

In [53]:
def FigVec(fig,vector1,vector2,vector3):
    data = go.Scatter3d(x=[origin[0],vector1[0]],y=[origin[1],vector1[1]],z=[origin[2],vector1[2]])
    data1 = go.Scatter3d(x=[origin[0],vector2[0]],y=[origin[1],vector2[1]],z=[origin[2],vector2[2]])
    data2 = go.Scatter3d(x=[origin[0],vector3[0]],y=[origin[1],vector3[1]],z=[origin[2],vector3[2]])
    fig.add_trace(data)
    fig.add_trace(data1)
    fig.add_trace(data2)
    return fig
    

In [54]:
xtheta = current_data[3]
ytheta = current_data[4]
ztheta = current_data[5]

R = EulerAngle(xtheta,ytheta,ztheta)
print(R)

origin = [0,0,0]
vectorx = np.asarray([R[0,0],R[1,0],R[2,0]])
vectory = np.asarray([R[0,1],R[1,1],R[2,1]])
vectorz = np.asarray([R[0,2],R[1,2],R[2,2]])

fig = go.Figure()
theta = np.linspace(0,2*pi,20)
phi = np.linspace(0,pi,10)
for i in range(0,len(theta)):
    for j in range(0,len(phi)):
        Rod_y = OrientMatixRotation(vectorx,vectory,theta[i])
#         fig = FigVec(fig,vectorx,Rod_y,vectorz)
        Rod_xy = OrientMatixRotation(Rod_y,vectorx,phi[j])
        Rod_y1 = OrientMatixRotation(Rod_xy,Rod_y,theta[i])
        fig = FigVec(fig,Rod_xy,Rod_y1,vectorz)
            

fig.show()



[[ 3.66872162e-01 -7.95693491e-01  4.81950915e-01]
 [-4.81951220e-01 -6.05699486e-01 -6.33128071e-01]
 [ 7.95693306e-01  2.32776076e-07 -6.05699729e-01]]


In [ ]:
#stop robot
robo.stop()

[array([0.12515173, 0.33089109, 0.93533316]), array([-0.02139805,  0.94342633, -0.33089104]), array([-0.99190683,  0.02139728,  0.12515186])]
