In [2]:
import urx
import math
from math import *
import math3d as m3d
import numpy as np
import time
import plotly.graph_objects as go
import socket 
import math
import plotly.io as pio
import os
import tqdm

In [2]:
#Connection Establishment
# robo = urx.Robot("127.0.0.1")
robo = urx.Robot("172.16.101.225")

tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 68
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1092
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1454


In [6]:
robo.movej((0,-math.pi/2,math.pi/2,0,math.pi/2,math.pi),0.2,0.2,relative=False,wait=False)
p0= robo.getl()
print(p0)

[-0.6032459616055122, -0.06251028216853388, 0.4190437170852153, 0.19854828021344278, -0.1120877474803198, 0.5746481631061161]


Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\ProgramFiles\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 286, in run
    data = self._get_data()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
socket.timeout: timed out



In [ ]:
robo.movej([3.6079858343316016e-11, -1.513388130396497, 1.697370813323119, -0.18398268292112974, 1.5707960000001053, 3.1415929999999714],0.2,0.2,relative = False,wait = False)
time.sleep(2)
p1 = robo.getl()
robo.movej([4.803220659048962e-11, -1.4944011977601805, 1.7392338448315048, -0.2448326470640101, 1.5707960000000931, 3.141592999999975],0.2,0.2,relative=False,wait=False)
time.sleep(2)
p2= robo.getl()
robo.movej([8.892868488398877e-11, -1.4294349951058294, 1.8824735266059736, -0.45303853148659456, 1.570796000000051, 3.1415929999999865],0.2,0.2,relative=False,wait=False)
time.sleep(2)
p3 = robo.getl()
robo.movej([1.2122860749991928e-10, -1.3781248724266364, 1.9956038211912968, -0.6174789487461858, 1.5707960000000178, 3.141592999999996],0.2,0.2,relative=False,wait=False)
time.sleep(2)
p4 = robo.getl()
robo.movej([1.3184566920153055e-10, -1.3612591125646123, 2.032790019196039, -0.6715309066113333, 1.570796000000007, 3.141592999999999],0.2,0.2,relative=False,wait=False)
time.sleep(2)
robo.movej([1.3721939066439846e-10,-1.3527226739241192,2.051611447945032,-0.6988887740,1.570796000,3.14159300],0.2,0.2,relative=False,wait=False)
p5 = robo.getl()
print(p1,p2)
# time.sleep(2)

In [ ]:
pio.renderers.default = "notebook"

In [ ]:
# HOST = "192.168.56.1"
HOST = "127.0.0.1"
PORT = 30002
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
# joint_angles = [[3.6079858343316016e-11, -1.513388130396497, 1.697370813323119, -0.18398268292112974, 1.5707960000001053, 3.1415929999999714],
#                [4.803220659048962e-11, -1.4944011977601805, 1.7392338448315048, -0.2448326470640101, 1.5707960000000931, 3.141592999999975],
#                [8.892868488398877e-11, -1.4294349951058294, 1.8824735266059736, -0.45303853148659456, 1.570796000000051, 3.1415929999999865],
#                [3.2122860749991928e-10, -3.3781248724266364, 1.9956038211912968, -0.6174789487461858, 1.5707960000000178, 3.141592999999996],
#                [1.3184566920153055e-10, -1.3612591125646123, 2.032790019196039, -0.6715309066113333, 1.570796000000007, 3.141592999999999],
#                [1.3721939066439846e-10,-1.3527226739241192,2.051611447945032,-0.6988887740,1.570796000,3.14159300]]
# s.send (("movej([1, -1.5707, -1.5707, 0, 1.5707, -1.5707], a=0.25, v=0.25)"+"\n").encode('utf8'))

# for i in range(len(joint_angles)):
#     c =joint_angles[i]
#     message = "movej(c,a=0.2,v=0.2,r=0.05)"
#     s.send((message+"\n").encode("utf8"))
tstart1 = time.time()
s.send (("movej([3.6079858343316016e-11, -1.513388130396497, 1.697370813323119, -0.18398268292112974, 1.5707960000001053, 3.1415929999999714],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))
tend1 = time.time()
sleeptime1 = tend1-tstart1
time.sleep(sleeptime1)
pose1 = robo.getl()

tstart2 = time.time()
s.send (("movej([4.803220659048962e-11, -1.4944011977601805, 1.7392338448315048, -0.2448326470640101, 1.5707960000000931, 3.141592999999975],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))
tend2 = time.time()
sleeptime2 = tend2-tstart2
time.sleep(sleeptime2)
pose2 = robo.getl()

tstart3 = time.time()
s.send (("movej([8.892868488398877e-11, -1.4294349951058294, 1.8824735266059736, -0.45303853148659456, 1.570796000000051, 3.1415929999999865],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))
tend3 = time.time()
sleeptime3 = tend3-tstart3
time.sleep(sleeptime3)
pose3 = robo.getl()

tstart4 = time.time()
s.send (("movej([9.2122860749991928e-10, -1.3781248724266364, 1.9956038211912968, -0.6174789487461858, 1.5707960000000178, 3.141592999999996],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))
tend4 = time.time()
sleeptime4 = tend4-tstart4
time.sleep(sleeptime4)
pose4 = robo.getl()

tstart5 = time.time()
s.send (("movej([8.3184566920153055e-10, -1.3612591125646123, 2.032790019196039, -0.6715309066113333, 1.570796000000007, 3.141592999999999],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))
tend5 = time.time()
sleeptime5 = tend5-tstart5
time.sleep(sleeptime5)
pose5 = robo.getl()

tstart6 = time.time()
s.send (("movej([4.3721939066439846e-10,-1.3527226739241192,2.051611447945032,-0.6988887740,1.570796000,3.14159300],a=0.2,v=0.2)"+"\n").encode('utf8'))
tend6 = time.time()
sleeptime6 = tend6-tstart6
time.sleep(sleeptime6)
pose6 = robo.getl()

s.send (("movej([1.3721939066439846e-10,-1.3527226739241192,2.051611447945032,-0.6988887740,1.570796000,3.14159300],a=0.2,v=0.2)"+"\n").encode('utf8'))
pose7 = robo.getl()

# s.send(("stopj(a=0.2)"+"\n").encode('utf8'))
# s.send (message)
# message1 = "movej([-1.95, -1.66, 1.71, -1.62, -1.56, 1.19], a=1.0, v=0.1)" + "\n"
# s.send (message1.encode('utf-8'))

print(pose5)
# print ("Received", repr(data))

In [ ]:
d = 0
c = 0
e = 0
if d == 0:
    s.send(("movec([0,-1.57,1.57,0,1.57,3.14],[3.6079858343316016e-11, -1.513388130396497, 1.697370813323119, -0.18398268292112974, 1.5707960000001053, 3.1415929999999714],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))
if c == 0:
    s.send(("movec([4.803220659048962e-11, -1.4944011977601805, 1.7392338448315048, -0.2448326470640101, 1.5707960000000931, 3.141592999999975],[8.892868488398877e-11, -1.4294349951058294, 1.8824735266059736, -0.45303853148659456, 1.570796000000051, 3.1415929999999865],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))
if e == 0:
    s.send(("movec([5.2122860749991928e-10, -1.3781248724266364, 1.9956038211912968, -0.6174789487461858, 1.5707960000000178, 3.141592999999996],[1.3721939066439846e-10,-1.3527226739241192,2.051611447945032,-0.6988887740,1.570796000,3.14159300],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))

In [ ]:
s.send(("movec([4.803220659048962e-11, -6.4944011977601805, 1.7392338448315048, -0.2448326470640101, 1.5707960000000931, 3.141592999999975],[8.892868488398877e-11, -1.4294349951058294, 1.8824735266059736, -0.45303853148659456, 1.570796000000051, 3.1415929999999865],a=0.2,v=0.2,r=0.05)"+"\n").encode('utf8'))

In [ ]:
robo.getj()

In [ ]:
[-0.510875215532435, -0.13330003278340555, 0.3017819719948155, -1.2091996760919022, -1.2091996534052114, 1.2092000720188498]
[-0.49194400828581303, -0.13330003260869513, 0.22579154136526328, -1.2091996762415516, -1.2091996531843943, 1.2092000717901772]

In [ ]:
s.close()

In [ ]:
xpt = [p0[0],p1[0],p2[0],p3[0],p4[0],p5[0]]
ypt = [p0[1],p1[1],p2[1],p3[1],p4[1],p5[1]]
zpt = [p0[2],p1[2],p2[2],p3[2],p4[2],p5[2]]

xpts = [pose1[0],pose2[0],pose3[0],pose4[0],pose5[0],pose6[0],pose7[0]]
ypts = [pose1[1],pose2[1],pose3[1],pose4[1],pose5[1],pose6[1],pose7[1]]
zpts = [pose1[2],pose2[2],pose3[2],pose4[2],pose5[2],pose6[2],pose7[2]]

# fig = go.Figure()
fig1 = go.Figure()
# data = go.Scatter3d(x=xpt,y=ypt,z=zpt)
data1 = go.Scatter3d(x=xpts,y=ypts,z=zpts)
fig1.add_trace(data)
fig1.add_trace(data1)
fig1.show()

In [ ]:
# import socket
# import time
# HOST = "127.0.0.1"      # The remote host
# PORT = 30002               # The same port as used by the server

# print("Starting Program")
# s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)        # Create a socket object
# count = 0
# count_2 = 0
# data = 0

# s.bind((HOST,PORT))        # Bind to the port
# s.listen(10)                 # Now wait for client connection.
# c, addr = s.accept()        # Establish connection with client.
# # # print(c)
# # c = s.connect((HOST, PORT))



# while (count < 1):

#     count = count + 1
#     print("The count is:", count)
#     time.sleep(0.5)
#     print("")
#     msg = c.recv(1024)
#     print("The robot position is(XYZ vector)")
#     print(msg)
#     print("")
#     time.sleep(0.5)
#     msg = s.recv(1024)
#     print("The robot position is(Joint angle)")
#     print(msg)

#     while (count_2 < 3):
#         count_2 = count_2 + 1
#         print("")
#         msg = c.recv(1024)
#         print(msg)
#         time.sleep(1)
#         if msg == "Asking_Waypoint_1":
#             c.send("(0.1,0.4,0.4,0.01,3.14,0.01)".encode('utf8'))
#         if msg == "Asking_Waypoint_2":
#             c.send("(0.1,0.4,0.3,0.01,3.14,0.01)".encode('utf8'))
#         if msg == "Asking_Waypoint_3":
#             c.send("(0.1,0.4,0.2,0.01,3.14,0.01)".encode('utf8'))
#     print("")
#     msg = c.recv(1024)
#     print("The robot position is(XYZ vector)")
#     print(msg)
#     print("")
#     msg = c.recv(1024)
#     print("The robot position is(Joint angle)")
#     print(msg)

# s.close()

# print("Program finish")

In [ ]:
SEPARATOR = "<SEPARATOR>"

filename = "E:/HTIC/example.script.txt"
filesize = os.path.getsize(filename)
BUFFER_SIZE = 4096

HOST = "127.0.0.1"
PORT = 30002
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

s.send(f"{filename}{SEPARATOR}{filesize}".encode('utf8'))

progress = tqdm.tqdm(range(filesize), f"Sending {filename}", unit="B", unit_scale=True, unit_divisor=1024)
with open(filename, "rb") as f:
    for _ in progress:
        # read the bytes from the file
        bytes_read = f.read(BUFFER_SIZE)
        if not bytes_read:
            # file transmitting is done
            break
        # we use sendall to assure transimission in 
        # busy networks
        s.sendall(bytes_read)
        # update the progress bar
        progress.update(len(bytes_read))
# close the socket
s.close()

In [ ]:
x = [-400.0, -399.31098008535633, -398.6219601707126, -397.9329402560689,
          -397.24392034142517, -396.5549004267815, -398.008053817019,
          -399.46120720725656, -403.0565339023753, -410.93620720725653,
          -420.95805381701905, -430.9799004267815, -443.1439203414252,
          -455.30794025606895, -467.4719601707126, -479.6359800853563, -491.8]

y = [150.0, 152.12635448604095, 154.2527089720819, 156.37906345812289,
          158.50541794416384, 160.63177243020482, 156.1472587542321,
          151.66274507825943, 140.5673632402731, 116.25024507825941,
          85.32225875423211, 54.39427243020481, 16.855417944163847,
          -20.683436541877114, -58.22229102791809, -95.76114551395905, -133.3]

z = [200.0, 239.55988144218097, 279.119762884362, 318.679644326543,
          358.2395257687241, 397.79940721090503, 430.1684948390257,
          462.5375824671464, 487.7158762812067, 498.5125824671464,
          502.11849483902574, 505.72440721090504, 502.13952576872407,
          498.5546443265431, 494.969762884362, 491.38488144218104, 487.8]

HOST = "127.0.0.1"
PORT = 30002
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

x = np.asarray(x)/1000
y = np.asarray(y)/1000
z = np.asarray(z)/1000
x = np.flip(x)
y = np.flip(y)
z = np.flip(z)

# print(x,y,z)
current_data = []

s.send (("movej([-0.01972178,-1.1790492171795863,1.027477877179586,1.3820527,1.47352838,-0.8946759771795865],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c1 = robo.getl()
s.send (("movej([-0.10792699,-1.2728126571795864,1.1323058871795864,1.25923211,1.43413444,-0.7373588771795863],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c2 = robo.getl()
s.send (("movej([-0.2004992,-1.3489057971795866,1.212839807179586,1.17092807,1.40073096,-0.574171077179586],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c3 = robo.getl()
s.send (("movej( [-0.29658444,-1.4092107471795865,1.2726016571795862,1.11029739,1.37326276,-0.40797058717958645],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c4 = robo.getl()
s.send (("movej( [-0.39477707,-1.454213017179586,1.3134998571795862,1.07382059,1.35244608,-0.2405788671795861],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c5 = robo.getl()
s.send (("movej([-0.49318585,-1.4835423471795863,1.3363651971795862,1.06017123,1.3395368,-0.07338652717958638],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c6 = robo.getl()
s.send (("movej([-0.57305318,-1.4983629271795866,1.3618445871795863,1.0469774,1.33517359,0.1061034 ],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c7 = robo.getl()
s.send (("movej([-0.64987497,-1.4995989271795862,1.373201087179586,1.05519025,1.3398495,0.28333883],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c8 = robo.getl()
s.send (("movej( [-0.70681586,-1.4906375171795858,1.3928544071795859,1.06266757,1.35261237,0.47117606],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c9 = robo.getl()
s.send (("movej([-0.73118591,-1.4838479071795865,1.4513662671795862,1.02539464,1.36301741,0.56568724],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c10 = robo.getl()
s.send (("movej([-0.74129918,-1.480079827179586,1.5302284171795861,0.94981588,1.36574095,0.55593163],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c11 = robo.getl()
###
s.send (("movej( [-0.75136443,-1.4699792571795864,1.602414207179586,0.87435617,1.368415,0.54623801],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c12 = robo.getl()
s.send (("movej( [-0.74659807,-1.4545258571795863,1.6875225771795863,0.77058513,1.36715323,0.5508265 ],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c13 = robo.getl()
s.send (("movej([-0.74182065,-1.4296523271795865,1.763938787179586,0.66603634,1.36588038,0.55542904],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c14 = robo.getl()
s.send (("movej([-0.73703241,-1.3952017671795867,1.831810397179586,0.56040465,1.36459641,0.56004553],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c15 = robo.getl()
s.send (("movej( [-0.73223358,-1.3510544471795862,1.8910541171795865,0.45365294,1.36330128,0.56467586],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c16 = robo.getl()
s.send (("movej( [-0.72742439,-1.2972231671795864,1.9414197371795865,0.34604345,1.36199495,0.56931991],a=0.2,v=0.2)"+"\n").encode('utf8'))
time.sleep(2)
c17 = robo.getl()


print(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16,c17,sep=",")



# for i in range(len(x)):
#     robo.movel([x[i],y[i],z[i],-1.2091996760919022, -1.2091996534052114, 1.2092000720188498],0.2,0.2,relative=False,wait=False)
#     time.sleep(2)
#     current = robo.getl()
#     current_data.append(current)
print(current_data)

In [ ]:
robo.movel?

In [ ]:
robo.stop()

In [ ]:
print([[1.7763568394002505e-15, -1.5707959999999979, 1.5707960000000014, 3.552713678800501e-15, 1.5707959999999996, 3.141593], [1.7763568394002505e-15, -1.5707959999999979, 1.5707960000000014, 3.552713678800501e-15, 1.5707959999999996, 3.141593], [-9.185755824425712e-05, -1.5708522738895994, 1.5708435000359537, 8.774260560582067e-06, 1.570704142348619, 3.141593000074666], [-0.0010649992096460892, -1.571447805011088, 1.5713459197138708, 0.00010188792608632111, 1.569731000188603, 3.1415930004798662], [-0.002929710624333559, -1.5725857108211319, 1.5723045889987644, 0.00028112730728049965, 1.5678662881201042, 3.141593000991025], [-0.004778365705724319, -1.5737096364545744, 1.5732497697923846, 0.0004598742845912011, 1.5660176325493638, 3.14159300136318], [-0.006616756047974626, -1.574823204821179, 1.5741845699624395, 0.000638644149825331, 1.5641792418250662, 3.1415930016445643], [-0.008152574918361744, -1.5757503899127654, 1.575001903599136, 0.0007484967772856181, 1.562643422686209, 3.141593001836071], [-0.009751349972578538, -1.5767126006210956, 1.575887177818337, 0.0008254343268498996, 1.5610446473891932, 3.1415930020037472], [-0.011591392259424182, -1.5778162926847052, 1.5769775321995327, 0.0008387731109615126, 1.5592046048501054, 3.1415930021720913], [-0.013262270152969435, -1.578815114523394, 1.5780769862902744, 0.0007381418194034189, 1.5575337267366611, 3.141593002314633], [-0.015063038969133302, -1.5798879788236366, 1.5794820712452997, 0.0004059221716985757, 1.555732957689952, 3.1415930024599126], [-0.01671592676269107, -1.5808692825851782, 1.5809314401525199, -6.214206434673741e-05, 1.5540800696881742, 3.141593002587595], [-0.01842851338163598, -1.5818822869090896, 1.5826607444513632, -0.0007784410948774578, 1.5523674828530742, 3.1415930027170145], [-0.01986982724467623, -1.5827315360000807, 1.5843074324692, -0.0015758792222388962, 1.5509261688070664, 3.1415930028241768], [-0.021340434103596984, -1.5835944719538553, 1.5861871126490774, -0.0025926226276080655, 1.5494555617603363, 3.141593002931937], [-0.022590195620519005, -1.5843244536874854, 1.5879749500219094, -0.0036504775643910747, 1.5482058000826933, 3.141593003022401]])

In [57]:
HOST = "172.16.101.225"
PORT = 30002
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
s.send (("movej([-0.74182065,-1.4296523271795865,1.763938787179586,0.66603634,1.36588038,0.55542904],a=0.2,v=0.2)"+"\n").encode('utf8'))
s.close()

In [151]:
-2*pi +5.10413609

-1.1790492171795863

In [5]:
jv =[[-0.00827245,  4.78395552, -4.29989256, -1.90846923,  1.52998398,  5.95231675],
[ 0.04425152  ,4.73556624 ,-4.27425402 ,-1.80591659  ,1.50564619  ,5.78043978],
[ 0.09611825  ,4.68172942 ,-4.25975956 ,-1.64790177  ,1.46840896  ,5.60982502],
[ 0.14344986  ,4.61918805 ,-4.26983944 ,-1.37664068  ,1.4059148   ,5.44043202],
[ 0.18174406  ,4.56732642 ,-4.35338244 ,-0.87459674  ,1.30260712  ,5.25728284],
[ 0.22260736  ,4.62789794 ,-4.58185051 ,-0.10433907  ,1.21827855 , 5.03422296],
[ 0.28819746  ,4.78107707 ,-4.81053231  ,0.52451481  ,1.26675894  ,4.91721397],
[ 0.35541157  ,4.88883393 ,-4.91886197  ,0.83493361  ,1.34086947  ,4.96846463],
[ 0.41293072  ,4.95370643 ,-4.95649094  ,0.97537745  ,1.39030076  ,5.08923919],
[ 0.4596364   ,4.98647915 ,-4.9488579   ,1.00225056  ,1.41182448  ,5.17561761],
[ 0.49833752  ,5.00529649 ,-4.91928731  ,0.97258893  ,1.41882201  ,5.20587103],
[ 0.53206546  ,5.02603777 ,-4.88541759  ,0.93278801  ,1.42456531  ,5.23286601],
[ 0.56133913  ,5.04952994 ,-4.84892154  ,0.88462862  ,1.42930441  ,5.25671314],
[ 0.58684608  ,5.07657092 ,-4.81169199  ,0.82995471  ,1.43326129  ,5.27777493],
[ 0.60939758  ,5.10782057 ,-4.77571563  ,0.77070316  ,1.43663465  ,5.29659617],
[ 0.62988759  ,5.14369156 ,-4.74294323  ,0.70891677  ,1.43960382  ,5.31384674],
[ 0.64925395  ,5.18426006 ,-4.71516835  ,0.64673395  ,1.44233074  ,5.33027315]]
for i in range(len(jv)):
    for j in range(len(jv[0])):
        if jv[i][j] >= 4:
            jv[i][j] = -2*pi + jv[i][j]
        if jv[i][j] <= -4:
            jv[i][j] = 2*pi + jv[i][j]
            
print(jv)

[[-0.00827245, -1.499229787179586, 1.9832927471795863, -1.90846923, 1.52998398, -0.33086855717958663], [0.04425152, -1.5476190671795864, 2.0089312871795864, -1.80591659, 1.50564619, -0.5027455271795862], [0.09611825, -1.6014558871795863, 2.0234257471795862, -1.64790177, 1.46840896, -0.6733602871795865], [0.14344986, -1.6639972571795862, 2.013345867179586, -1.37664068, 1.4059148, -0.842753287179586], [0.18174406, -1.7158588871795866, 1.9298028671795864, -0.87459674, 1.30260712, -1.025902467179586], [0.22260736, -1.6552873671795858, 1.7013347971795865, -0.10433907, 1.21827855, -1.248962347179586], [0.28819746, -1.502108237179586, 1.472652997179586, 0.52451481, 1.26675894, -1.3659713371795865], [0.35541157, -1.3943513771795866, 1.3643233371795862, 0.83493361, 1.34086947, -1.3147206771795865], [0.41293072, -1.3294788771795858, 1.326694367179586, 0.97537745, 1.39030076, -1.1939461171795864], [0.4596364, -1.2967061571795861, 1.334327407179586, 1.00225056, 1.41182448, -1.1075676971795865], [0

In [ ]:
robo.is_running?

In [ ]:
print(len(current_value))

In [13]:
joint_angles =np.asarray( [[-0.01972178,-1.1790492171795863,1.027477877179586,1.3820527,1.47352838,-0.8946759771795865],
               [-0.10792699,-1.2728126571795864,1.1323058871795864,1.25923211,1.43413444,-0.7373588771795863],
               [-0.2004992,-1.3489057971795866,1.212839807179586,1.17092807,1.40073096,-0.574171077179586],
               [-0.29658444,-1.4092107471795865,1.2726016571795862,1.11029739,1.37326276,-0.40797058717958645],
               [-0.39477707,-1.454213017179586,1.3134998571795862,1.07382059,1.35244608,-0.2405788671795861],
               [-0.49318585,-1.4835423471795863,1.3363651971795862,1.06017123,1.3395368,-0.07338652717958638],
               [-0.57305318,-1.4983629271795866,1.3618445871795863,1.0469774,1.33517359,0.1061034 ],
               [-0.64987497,-1.4995989271795862,1.373201087179586,1.05519025,1.3398495,0.28333883],
               [-0.70681586,-1.4906375171795858,1.3928544071795859,1.06266757,1.35261237,0.47117606],
               [-0.73118591,-1.4838479071795865,1.4513662671795862,1.02539464,1.36301741,0.56568724],
               [-0.74129918,-1.480079827179586,1.5302284171795861,0.94981588,1.36574095,0.55593163],
               [-0.75136443,-1.4699792571795864,1.602414207179586,0.87435617,1.368415,0.54623801],
               [-0.74659807,-1.4545258571795863,1.6875225771795863,0.77058513,1.36715323,0.5508265 ],
               [-0.74182065,-1.4296523271795865,1.763938787179586,0.66603634,1.36588038,0.55542904],
               [-0.73703241,-1.3952017671795867,1.831810397179586,0.56040465,1.36459641,0.56004553],
               [-0.73223358,-1.3510544471795862,1.8910541171795865,0.45365294,1.36330128,0.56467586],
                [-0.72742439,-1.2972231671795864,1.9414197371795865,0.34604345,1.36199495,0.56931991]])

HOST = "127.0.0.1"
PORT = 30002
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

theta = []
current_val = []
for i in range(len(joint_angles)-1):
    thetaa = joint_angles[i+1] - joint_angles[i]
    theta.append(thetaa)
    print(thetaa+joint_angles[i])
# print(theta)
theta = np.asarray(theta)
velocity_q = theta/3
# print(velocity_q)
a=0.1
t=3
a = "a = " + str(a)
t = "t = " + str(t)
for i in range (len(velocity_q)):
    message = str(list(velocity_q[i]))
#     print(message)
    speedj = "speedj"+"("+message+","+a+","+t+")"+"\n"
#     print(speedj)
    s.send(speedj.encode('utf8'))
    time.sleep(3)
    
    curr = robo.getj()
    current_val.append(curr)
print(current_val)
    
s.close()

[-0.10792699 -1.27281266  1.13230589  1.25923211  1.43413444 -0.73735888]
[-0.2004992  -1.3489058   1.21283981  1.17092807  1.40073096 -0.57417108]
[-0.29658444 -1.40921075  1.27260166  1.11029739  1.37326276 -0.40797059]
[-0.39477707 -1.45421302  1.31349986  1.07382059  1.35244608 -0.24057887]
[-0.49318585 -1.48354235  1.3363652   1.06017123  1.3395368  -0.07338653]
[-0.57305318 -1.49836293  1.36184459  1.0469774   1.33517359  0.1061034 ]
[-0.64987497 -1.49959893  1.37320109  1.05519025  1.3398495   0.28333883]
[-0.70681586 -1.49063752  1.39285441  1.06266757  1.35261237  0.47117606]
[-0.73118591 -1.48384791  1.45136627  1.02539464  1.36301741  0.56568724]
[-0.74129918 -1.48007983  1.53022842  0.94981588  1.36574095  0.55593163]
[-0.75136443 -1.46997926  1.60241421  0.87435617  1.368415    0.54623801]
[-0.74659807 -1.45452586  1.68752258  0.77058513  1.36715323  0.5508265 ]
[-0.74182065 -1.42965233  1.76393879  0.66603634  1.36588038  0.55542904]
[-0.73703241 -1.39520177  1.8318104   

In [4]:
current_value = []
for i in range(100):
    c = robo.getl()
    current_value.append(c)
    time.sleep(0.2)
print(current_value)    

[[-0.4932288435631953, -0.1234461458882571, 0.482767372220726, -0.9599581086571766, -1.4810248956855265, 0.8455442293662414], [-0.49327352065004987, -0.12170078718209622, 0.4819393439741406, -0.9074328281938306, -1.5282249389239295, 0.7803629738072068], [-0.49323718098887787, -0.11994068654169111, 0.481197595035805, -0.8531542360081807, -1.5741330935061726, 0.7160009216457364], [-0.4931985480958556, -0.1181759060647878, 0.4804728454325717, -0.7964109804615596, -1.61896485894151, 0.6519974429223692], [-0.493153008320518, -0.11643693482126438, 0.4797067398051799, -0.7386048813076063, -1.662231881811687, 0.5896893214590653], [-0.4929766591486561, -0.11464285902894542, 0.47909978685331517, -0.679022589998184, -1.703881560664272, 0.5283074375683037], [-0.4927311401240641, -0.11292423533623501, 0.478639105023809, -0.6167070270766121, -1.7441478312729308, 0.4675836882450919], [-0.4924540504420892, -0.11125909993121495, 0.4780724062081127, -0.5533360994532898, -1.7827687984763538, 0.4086364432

Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\ProgramFiles\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 286, in run
    data = self._get_data()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
socket.timeout: timed out



In [ ]:
robo.is_program_running()

In [17]:
robo.getl()

[-0.39385426207195795,
 0.09595160403692587,
 0.2386446264451209,
 -1.6650728735910674,
 0.14293051209408036,
 1.8638299950714443]

In [28]:
joint_angles =np.asarray( [[-0.01972178,-1.1790492171795863,1.027477877179586,1.3820527,1.47352838,-0.8946759771795865],
               [-0.10792699,-1.2728126571795864,1.1323058871795864,1.25923211,1.43413444,-0.7373588771795863],
               [-0.2004992,-1.3489057971795866,1.212839807179586,1.17092807,1.40073096,-0.574171077179586],
               [-0.29658444,-1.4092107471795865,1.2726016571795862,1.11029739,1.37326276,-0.40797058717958645],
               [-0.39477707,-1.454213017179586,1.3134998571795862,1.07382059,1.35244608,-0.2405788671795861],
               [-0.49318585,-1.4835423471795863,1.3363651971795862,1.06017123,1.3395368,-0.07338652717958638],
               [-0.57305318,-1.4983629271795866,1.3618445871795863,1.0469774,1.33517359,0.1061034 ],
               [-0.64987497,-1.4995989271795862,1.373201087179586,1.05519025,1.3398495,0.28333883],
               [-0.70681586,-1.4906375171795858,1.3928544071795859,1.06266757,1.35261237,0.47117606],
               [-0.73118591,-1.4838479071795865,1.4513662671795862,1.02539464,1.36301741,0.56568724],
               [-0.74129918,-1.480079827179586,1.5302284171795861,0.94981588,1.36574095,0.55593163],
               [-0.75136443,-1.4699792571795864,1.602414207179586,0.87435617,1.368415,0.54623801],
               [-0.74659807,-1.4545258571795863,1.6875225771795863,0.77058513,1.36715323,0.5508265 ],
               [-0.74182065,-1.4296523271795865,1.763938787179586,0.66603634,1.36588038,0.55542904],
               [-0.73703241,-1.3952017671795867,1.831810397179586,0.56040465,1.36459641,0.56004553],
               [-0.73223358,-1.3510544471795862,1.8910541171795865,0.45365294,1.36330128,0.56467586],
                [-0.72742439,-1.2972231671795864,1.9414197371795865,0.34604345,1.36199495,0.56931991]])

HOST = "127.0.0.1"
PORT = 30002
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

thetaa = joint_angles[11] - joint_angles[10]
velocity_q = thetaa/3

a=0.1
t=5
a = "a = " + str(a)
t = "t = " + str(t)
message = str(list(velocity_q))
#     print(message)
speedj = "speedj"+"("+message+","+a+","+t+")"+"\n"
#     print(speedj)
# s.send (("movej([-0.74129918,-1.480079827179586,1.5302284171795861,0.94981588,1.36574095,0.55593163],a=0.2,v=0.2)"+"\n").encode('utf8'))
s.send(speedj.encode('utf8'))
# curr = robo.getj()
# #     current_val.append(curr)
# print(curr)

159

Exception in thread Thread-7:
Traceback (most recent call last):
  File "E:\ProgramFiles\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 286, in run
    data = self._get_data()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
socket.timeout: timed out

Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\ProgramFiles\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 286, in run
    data = self._get_data()
  File "E:\ProgramFiles\anaconda3\lib\site-packages\urx\ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
socket.timeout: timed out



In [9]:
# jv_speedj = np.asarray([[-0.011255126904393897, -1.5827603660073208, 1.5841722229655717, -0.015672105161617544, 1.5657692697879853, 3.1616669154153283], [-0.02342744588439416, -1.5956997207273194, 1.5986384883455718, -0.032621346581617416, 1.5603329060679858, 3.183376675215328], [-0.033718053717727514, -1.6066387887273201, 1.6108684228455719, -0.046950415414950264, 1.5557369464013195, 3.2017303368819947], [-0.046596014377727535, -1.6203282509673187, 1.626173312305572, -0.06488222155495027, 1.5499854311613195, 3.224698633481995], [-0.059415171564393354, -1.633955204247318, 1.6414083164255708, -0.08273214730161627, 1.5442601785479866, 3.2475620520153266], [-0.07270475653772479, -1.6480822292073167, 1.6572024032655692, -0.10123711619494724, 1.53832482492132, 3.271264495081991], [-0.08575912761772386, -1.6619592183273149, 1.6727169487455675, -0.11941456351494573, 1.5324945218013202, 3.294547425881988], [-0.09851948133105548, -1.675523662647315, 1.687882067525566, -0.13718260886827682, 1.5267955318146544, 3.3173059663486524], [-0.11122103157105379, -1.6890255980073121, 1.7029773009655642, -0.1548687738282748, 1.5211228044546559, 3.33995962874865], [-0.12168804982438619, -1.7001521928873125, 1.715416891485563, -0.169443483841607, 1.5164480569079881, 3.3586279246153143], [-0.13468361743105106, -1.7139666730473095, 1.7308615516255612, -0.1875390507682715, 1.5106440164146555, 3.3818059773486455]])

# for i in range(len(jv_speedj)):
#     for j in range(len(jv_speedj[0])):
#         if joint_angles[1][j] <= jv_speedj[i][j]-0.004 or joint_angles[1][j]>=jv_speedj[i][j]:
#             print(True)
#         else:
#             print(False)

In [8]:
len(jv_speedj)

11

In [58]:


HOST = "127.0.0.1" # The UR IP address
PORT = 30002 # UR secondary client
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

filename = "F:/Codes/example.script"

f = open (filename, "rb")  

l = f.read(1024)
# print(l)
while (l):
    s.send(l)
    l = f.read(1024)
s.close()

In [11]:
robo.getl()

[-0.40001797201974254,
 0.1500862376961835,
 0.20099976515542042,
 0.4324562594335612,
 -2.545194339056036,
 -0.4109124199807574]

In [9]:
jv = [[-0.00827245, -1.499229787179586, 1.9832927471795863, -1.90846923, 1.52998398, -0.33086855717958663], [0.04425152, -1.5476190671795864, 2.0089312871795864, -1.80591659, 1.50564619, -0.5027455271795862], [0.09611825, -1.6014558871795863, 2.0234257471795862, -1.64790177, 1.46840896, -0.6733602871795865], [0.14344986, -1.6639972571795862, 2.013345867179586, -1.37664068, 1.4059148, -0.842753287179586], [0.18174406, -1.7158588871795866, 1.9298028671795864, -0.87459674, 1.30260712, -1.025902467179586], [0.22260736, -1.6552873671795858, 1.7013347971795865, -0.10433907, 1.21827855, -1.248962347179586], [0.28819746, -1.502108237179586, 1.472652997179586, 0.52451481, 1.26675894, -1.3659713371795865], [0.35541157, -1.3943513771795866, 1.3643233371795862, 0.83493361, 1.34086947, -1.3147206771795865], [0.41293072, -1.3294788771795858, 1.326694367179586, 0.97537745, 1.39030076, -1.1939461171795864], [0.4596364, -1.2967061571795861, 1.334327407179586, 1.00225056, 1.41182448, -1.1075676971795865], [0.49833752, -1.2778888171795861, 1.3638979971795866, 0.97258893, 1.41882201, -1.0773142771795863], [0.53206546, -1.257147537179586, 1.397767717179586, 0.93278801, 1.42456531, -1.0503192971795858], [0.56133913, -1.233655367179586, 1.4342637671795861, 0.88462862, 1.42930441, -1.0264721671795867], [0.58684608, -1.2066143871795862, 1.4714933171795863, 0.82995471, 1.43326129, -1.0054103771795866], [0.60939758, -1.175364737179586, 1.5074696771795866, 0.77070316, 1.43663465, -0.9865891371795863], [0.62988759, -1.1394937471795865, 1.5402420771795864, 0.70891677, 1.43960382, -0.9693385671795864], [0.64925395, -1.0989252471795865, 1.5680169571795863, 0.64673395, 1.44233074, -0.9529121571795862]]
a = 0.1
v = 0.1
r= 0.02
a = "a = " + str(a)
v = "v = " + str(v)
r = "r = " + str(r)
filename = "F:/Codes/example1.script"
f = open (filename, "wb")
f.write("def q():\n".encode("utf8"))
f.write("  while(True):\n".encode("utf8"))
for i in range (len(jv)):
    message = str(list(jv[i]))
#     print(message)
    if i == len(jv)-1:
        movej = "    "+"movej"+"("+message+","+a+","+v+")"+"\n"
        movej = movej.encode("utf8")
        f.write(movej)
    else:    
        movej = "    "+"movej"+"("+message+","+a+","+v+","+r+")"+"\n"
        movej = movej.encode("utf8")
        print(movej)
        f.write(movej)
f.write("    halt\n".encode("utf8"))
f.write("    end\n".encode("utf8"))
f.write("  end\n".encode("utf8"))
f.write("end\n".encode("utf8"))
f.close()
#     s.send(speedj.encode('utf8'))
#     time.sleep(3)

b'    movej([-0.00827245, -1.499229787179586, 1.9832927471795863, -1.90846923, 1.52998398, -0.33086855717958663],a = 0.1,v = 0.1,r = 0.02)\n'
b'    movej([0.04425152, -1.5476190671795864, 2.0089312871795864, -1.80591659, 1.50564619, -0.5027455271795862],a = 0.1,v = 0.1,r = 0.02)\n'
b'    movej([0.09611825, -1.6014558871795863, 2.0234257471795862, -1.64790177, 1.46840896, -0.6733602871795865],a = 0.1,v = 0.1,r = 0.02)\n'
b'    movej([0.14344986, -1.6639972571795862, 2.013345867179586, -1.37664068, 1.4059148, -0.842753287179586],a = 0.1,v = 0.1,r = 0.02)\n'
b'    movej([0.18174406, -1.7158588871795866, 1.9298028671795864, -0.87459674, 1.30260712, -1.025902467179586],a = 0.1,v = 0.1,r = 0.02)\n'
b'    movej([0.22260736, -1.6552873671795858, 1.7013347971795865, -0.10433907, 1.21827855, -1.248962347179586],a = 0.1,v = 0.1,r = 0.02)\n'
b'    movej([0.28819746, -1.502108237179586, 1.472652997179586, 0.52451481, 1.26675894, -1.3659713371795865],a = 0.1,v = 0.1,r = 0.02)\n'
b'    movej([0.35541